---
- name: "INCLUDE >> Logging setup"
  import_tasks: "log_setup.yml"
  when: "log"
  
- name: "INCLUDE >> {{ ansible_network_os }} tasks"
  include_tasks: "{{ ansible_network_os }}.yml"

- name: "INCLUDE >> Log write"
  import_tasks: "log_write.yml"
  when: "log"
...